name: Advent of Links Code

on:
  pull_request:
    branches: main
  push:
    branches: [main]
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.1.0

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: links
          POSTGRES_PASSWORD: links
        ports:
          - 5433:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt-get install -y libev-dev
        shell: bash

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install -y conf-libev

      - name: Install Links
        run: opam install -y links links-postgresql

        # TODO(dhil): Add AOC programs to this list.
      - name: Run AOC programs
        run: /usr/bin/true
        env:
          LINKS_POSTGRES_HOST: localhost
          LINKS_POSTGRES_USER: links
          LINKS_POSTGRES_PASSWORD: links
          LINKS_POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        shell: bash
